# Generated by Django 2.2.3 on 2020-03-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='starred',
            field=models.ManyToManyField(to='myapp.Story'),
        ),
    ]
