# Generated by Django 2.2.10 on 2020-03-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userprofile_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='short',
            field=models.TextField(default='', max_length=4),
        ),
    ]
