# Generated by Django 2.2.3 on 2020-04-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_story_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='short',
            field=models.TextField(default='☮', max_length=8),
        ),
    ]
